# Generated by Django 6.1 on 2026-08-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blocklistuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockListUser',
            new_name='BlockUser',
        ),
        migrations.RenameField(
            model_name='blockuser',
            old_name='user',
            new_name='username',
        ),
    ]
